### ISSUE TITLE
Auth example not working on Node v 8.11.2

### ISSUE THREAD

**Issue by danielhayes** [mateodelnorte/sourced#29]
`node examples/auth/example.js`
Results in the following with Node v 8.11.2:
```
matt was provisioned with pw saltypass
matt was granted access to app with id 1
matt was granted access to app with id 2
matt was revoked access to app with id 1
user matt has been modified with the following operations: [{"method":"provision","data":{"username":"matt","pass":"saltypass"},"timestamp":1531567220826,"version":1},{"method":"grant","data":{"name":"sales","appId":1},"timestamp":1531567220827,"version":2},{"method":"grant","data":{"name":"marketing","appId":2},"timestamp":1531567220827,"version":3},{"method":"revoke","data":{"name":"sales","appId":1},"timestamp":1531567220827,"version":4}]
we could persist him with the following snapshot: {"apps":{"2":{"name":"marketing","appId":2}},"username":"matt","pass":"","password":"saltypass","snapshotVersion":4,"timestamp":1531567220827,"version":4,"_eventsCount":3}
/Users/dhayes/Development/Projects/sandbox/sourced/lib/entity.js:165
      this.mergeProperty(property, val);
           ^

TypeError: this.mergeProperty is not a function
    at User.merge (/Users/dhayes/Development/Projects/sandbox/sourced/lib/entity.js:165:12)
    at User.Entity (/Users/dhayes/Development/Projects/sandbox/sourced/lib/entity.js:92:10)
    at new User (/Users/dhayes/Development/Projects/sandbox/sourced/examples/auth/user.js:10:10)
    at Object.<anonymous> (/Users/dhayes/Development/Projects/sandbox/sourced/examples/auth/example.js:26:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)


This is a fresh pull from master.
